CREATE DATABASE PLATAFORMA;

USE PLATAFORMA;

/*AUTORELACIONAMENTO*/

CREATE TABLE CURSOS(
	IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	HORAS INT,
	VALOR FLOAT(10,2),
	ID_PREREQ INT
);

ALTER TABLE CURSOS ADD CONSTRAINT FK_PREREQ
FOREIGN KEY(ID_PREREQ) REFERENCES CURSOS(IDCURSO);

INSERT INTO CURSOS VALUES (NULL, 'BANCO DE DADOS RELACIONAIS', 40, 200.00, NULL);
INSERT INTO CURSOS VALUES (NULL, 'POWER BI', 45, 250.00, 1);
INSERT INTO CURSOS VALUES (NULL, 'ANÁLISE DE DADOS', 50, 300.00, 2);
INSERT INTO CURSOS VALUES (NULL, 'LÓGICA DE PROGRAMAÇÃO', 40, 200.00, NULL);
INSERT INTO CURSOS VALUES (NULL, 'RUBY', 40, 200.00, 4);

SELECT NOME, VALOR, HORAS, IFNULL(ID_PREREQ, 'SEM REQUISITO') AS REQUISITO
FROM CURSOS;

SELECT C.NOME, C.VALOR, C.HORAS, IFNULL(P.NOME, 'SEM REQUISITO') AS REQUISITO
FROM CURSOS C 
LEFT JOIN CURSOS P
ON P.IDCURSO = C.ID_PREREQ;
