/* Modelagem Básica 
ENTIDADE = TABLEA
CAMPOS = ATRIBUTOS*/

CLIENTE

NOME - CARACTER(30)
CPF - NUMERICO(11)
EMAIL - CARACTER(30)
TELEFONE - CARACTER(30)
ENDERECO - CARACTER(100)
SEXO - CARACTER(1)

/* MODELAGEM FISICA */ 

/* CRIANDO BANCO DE DADOS */

CREATE DATABASE PROJETO;

/* CONECTANDO-SE AO BANCO DE DADOS */

USE PROJETO;

/* CRIANDO A TABELA DE CLIENTES */

CREATE TABLE CLIENTE (
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
);

/* VERIFICANDO AS TABELAS DO BANCO */

SHOW TABLES;

/* DESCOBRINDO COMO E A ESTRUTURA DE UMA TABELA */

DESC CLIENTE;

/* INSERCAO DE DADOS NA TABELA OMTINDO AS COLUNAS */

INSERT INTO CLIENTE VALUES('JOAO', 'M', 'JOAO@GMAIL.COM',12345678, '21965184561', 'DUQUE DE CAXIAS, PARQUE PAULISTA,
RUA OLIVEIRA LIMA, 25261260');

INSERT INTO CLIENTE VALUES('MARIA', 'F', 'MARIA@GMAIL.COM',12136457, '21965187654', 'DUQUE DE CAXIAS, PARQUE PAULISTA,
RUA DINAMARCA, 25261340');

INSERT INTO CLIENTE VALUES('JULIA', 'F', 'JULIA@GMAIL.COM',17655674, '21965188765', 'DUQUE DE CAXIAS, SANTA CRUZ DA SERRA,
RUA BRIGADEIRO LIMA, 25231450');

/* IINSERCAO DE DADOS NA TABELA COLOCANDO AS COLUNAS */

INSERT INTO CLIENTE(NOME, SEXO, ENDERECO, TELEFONE, CPF) VALUES('ANNA', 'F', 'RIO DE JANEIRO, COPACABANA, RUA MARCOS DE FREITAS, 56',
'21965184681', 14565477);

/* INSERCAO DE DADOS COMPACTA - APENAS MYSQL */

INSERT INTO CLIENTE VALUES ('IGOR', 'M', 'IGOR@OUTLOOK.COM', 12235676, '21965143241', 'RIO DE JANEIRO, IPANEMA, RUA PROCOPIO
FERREIRA, 67'), 
			('LUIS', 'M', 'LUIS@YAHOO.COM', 12239876, '21965167685', 'NITEROI, ICARAI, RUA PAULO FREIRE, 32');
			
/* COMANDO SELECT */

SELECT NOW() AS DATA_HORA;

SELECT 'ANNA CRISTINA' AS ALUNA;

SELECT NOME AS CLIENTE, SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, NOW() AS DATA_HORA FROM CLIENTE;

/* APENAS PARA FINS ACADEMICOS */

SELECT * FROM CLIENTE;

/* COMANDO WHERE */

SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'F';

SELECT NOME, EMAIL FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME, ENDERECO FROM CLIENTE
WHERE ENDERECO = 'DUQUE DE CAXIAS'; /* VAI INDICAR CAMPO VAZIO */

SELECT NOME, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE 'DUQUE DE CAXIAS%';