CREATE DATABASE LIVRARIA;

USE LIVRARIA;

CREATE TABLE LIVROS(
	NOME_LIVRO VARCHAR(30),
	NOME_AUTOR VARCHAR(30),
	SEXO_AUTOR CHAR(1),
	PAGINAS CHAR(5),
	NOME_EDITORA VARCHAR(30),
	VALOR FLOAT(6,2),
	ESTADO_EDITORA CHAR(2),
	ANO_PUBLICACAO CHAR(4)
);

INSERT INTO LIVROS(NOME_LIVRO, NOME_AUTOR, SEXO_AUTOR, PAGINAS, NOME_EDITORA, VALOR, ESTADO_EDITORA, ANO_PUBLICACAO)
VALUES('CAVALEIRO REAL', 'ANA CLAUDIA', 'F', '465', 'ATLAS', 49.9, 'RJ', '2009'),
	('SQL PARA LEIGOS', 'JOAO NUNES', 'M', '450','ADDISON', 98, 'SP', '2018'),
	('RECEITAS CASEIRAS','CELIA TAVARES', 'F', '210', 'ATLAS', 45, 'RJ', '2008'),
	('PESSOAS EFETIVAS', 'EDUARDO SANTOS', 'M', '390', 'BETA', 78.99, 'RJ', '2018'),
	('HABITOS SAUDÁVEIS', 'EDUARDO SANTOS', 'M', '630', 'BETA', 150.98, 'RJ', '2019'),
	('A CASA MARROM', 'HERMES MACEDO', 'M', '250', 'BUBBA', 60, 'MG', '2016'),
	('ESTACIO QUERIDO', 'GERALDO FRANCISCO', 'M', '310', 'INSIGNIA', 100, 'ES', '2015'),
	('PARA SEMPRE AMIGAS', 'LEDA SILVA', 'F', '510', 'INSIGNIA', 78.98, 'RS', '2018'),
	('COPAS INSESQUECIVEIS', 'MARCO ALCANTRA', 'M', '200', 'LARSON', 130.98, 'RS', '2018'),
	('O PODER DA MENTE', 'CLARA MAFRA', 'F', '120', 'CONTINENTAL', 56.58, 'SP', '2017');
	
SELECT * FROM LIVROS;

SELECT NOME_LIVRO, NOME_EDITORA FROM LIVROS;

SELECT NOME_LIVRO, ESTADO_EDITORA FROM LIVROS
WHERE SEXO_AUTOR = 'M';

SELECT NOME_LIVRO, PAGINAS FROM LIVROS
WHERE SEXO_AUTOR = 'F';

SELECT VALOR FROM LIVROS
WHERE ESTADO_EDITORA = 'SP';


SELECT NOME_LIVRO, NOME_AUTOR, NOME_EDITORA, ESTADO_EDITORA FROM LIVROS
WHERE 	SEXO_AUTOR = 'M' AND (ESTADO_EDITORA = 'RJ' OR ESTADO_EDITORA = 'SP');

/* OPERADOR COUNT(*) */

SELECT COUNT(*) FROM LIVROS;

SELECT SEXO_AUTOR, COUNT(*)
FROM LIVROS
GROUP BY SEXO_AUTOR;
	