CREATE DATABASE PROJETO;

USE PROJETO;

CREATE TABLE CURSOS(
	IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	HORAS INT(3) NOT NULL,
	VALOR FLOAT (10,2) NOT NULL
);

INSERT INTO CURSOS VALUES(NULL, 'BANCO DE DADOS', 30, 50.25);
INSERT INTO CURSOS VALUES(NULL, 'JAVA', 55, 100);

/*CRIANDO PROCEDURE DE CADASTRO*/

DELIMITER $

CREATE PROCEDURE CAD_CURSO(P_NOME VARCHAR(30),
						  P_HORAS INT(3),
						  P_VALOR FLOAT(10,2))
BEGIN
	INSERT INTO CURSOS VALUES(NULL, P_NOME, P_HORAS, P_VALOR);
END
$

CALL CAD_CURSO('CIÊNCIA DE DADOS', 60, 120);
CALL CAD_CURSO('LITERATURA CLASSICA', 20, 250);
CALL CAD_CURSO('EXCEL BASICO', 10, 25);
CALL CAD_CURSO('VUE JS', 35, 350);
CALL CAD_CURSO('ANATOMIA', 28, 550);
CALL CAD_CURSO('FOTOGRAFIA CONCEITUAL', 12, 75);

/* CRIANDO PROCEDURE DE CONSULTA DE CURSOS*/

DELIMITER $

CREATE PROCEDURE CONSUL_CURSOS()
BEGIN
	SELECT * FROM CURSOS;
END
$

CALL CONSUL_CURSOS();

/*FUNÇÕES DE AGREGAÇÃO NUMÉRICA*/

CREATE TABLE VENDEDORES(
	IDVENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	SEXO CHAR(1),
	JANEIRO FLOAT (10,2),
	FEVEREIRO FLOAT(10,2),
	MARCO FLOAT(10,2)
);

INSERT INTO VENDEDORES VALUES(NULL, 'CARLOS', 'M', 189.92, 912.91, 822.71);
INSERT INTO VENDEDORES VALUES(NULL, 'MARIA', 'F', 8282.21, 929.24, 7272.12);
INSERT INTO VENDEDORES VALUES(NULL, 'JOAO', 'M', 928.82, 982.91, 192.62);
INSERT INTO VENDEDORES VALUES(NULL, 'CAMILA', 'F', 8382.12, 736.26, 822.13);
INSERT INTO VENDEDORES VALUES(NULL, 'LUCAS', 'M', 182.92, 919.91, 822.1);
INSERT INTO VENDEDORES VALUES(NULL, 'PEDRO', 'M', 765.98, 651.21, 827.29);
INSERT INTO VENDEDORES VALUES(NULL, 'MARCOS', 'M', 122.92, 198.72, 199.76);
INSERT INTO VENDEDORES VALUES(NULL, 'LUCIA', 'F', 1892.92, 9192.19, 8271.21);
INSERT INTO VENDEDORES VALUES(NULL, 'DANIELA', 'F', 182.18, 9228.21, 821.90);

/*MAX - TRAZ O VALOR MAXIMO DE UMA COLUNA*/

SELECT MAX(FEVEREIRO) AS MAIOR_FEVEREIRO
FROM VENDEDORES;
+-----------------+
| MAIOR_FEVEREIRO |
+-----------------+
|         9228.21 |
+-----------------+

/*MIN - TRAZ O VALOR MIN DE UMA COLUNA*/

SELECT MIN(FEVEREIRO) AS MIN_FEVEREIRO
FROM VENDEDORES;
+---------------+
| MIN_FEVEREIRO |
+---------------+
|        198.72 |
+---------------+

/*AVG - TRAZ O VALOR MEDIO DE UMA COLUNA*/

SELECT AVG(FEVEREIRO) AS MEDIA_FEVEREIRO
FROM VENDEDORES;
+-----------------+
| MEDIA_FEVEREIRO |
+-----------------+
|     2639.062259 |
+-----------------+

/*VARIAS FUNCOES EM UMA QUERY*/

SELECT TRUNCATE(MIN(JANEIRO),2) AS MIN_JANEIRO,
	   TRUNCATE(MAX(JANEIRO),2) AS MAX_JANEIRO,
	   TRUNCATE(AVG(JANEIRO),2) AS MEDIA_JANEIRO
FROM VENDEDORES
WHERE SEXO = 'F';

SELECT TRUNCATE(MIN(JANEIRO),2) AS MIN_JANEIRO,
	   TRUNCATE(MAX(JANEIRO),2) AS MAX_JANEIRO,
	   TRUNCATE(AVG(JANEIRO),2) AS MEDIA_JANEIRO
FROM VENDEDORES 
WHERE SEXO = 'M';

/*SUM - SOMA OS VALORES DE UMA COLUNA*/

SELECT SUM(JANEIRO) AS TOTAL_JANEIRO
FROM VENDEDORES;
+---------------+
| TOTAL_JANEIRO |
+---------------+
|      20929.99 |
+---------------+

SELECT SUM(MARCO) AS TOTAL_MARCO
FROM VENDEDORES
WHERE SEXO = 'F';
+-------------+
| TOTAL_MARCO |
+-------------+
|    17187.36 |
+-------------+

SELECT SUM(MARCO) AS TOTAL_MARCO
FROM VENDEDORES
WHERE SEXO = 'M';
| TOTAL_MARCO |
+-------------+
|     2864.48 |
+-------------+

SELECT SEXO, SUM(MARCO) AS TOTAL_MARCO
FROM VENDEDORES
GROUP BY SEXO;

/*VENDEDOR QUE VENDEU MENOS EM MARCO E O VALOR*/

SELECT NOME
FROM VENDEDORES
WHERE MARCO = MIN(MARCO); /*FORMA ERRADA*/

SELECT NOME, MARCO
FROM VENDEDORES 
WHERE MARCO = (SELECT MIN(MARCO) FROM VENDEDORES); /*FORMA CORRETA*/

SELECT MIN(MARCO) FROM VENDEDORES;

/*VENDEDOR QUE VENDEU MAIS EM MARCO E O VALOR*/

SELECT NOME, MARCO
FROM VENDEDORES
WHERE MARCO = (SELECT MAX(MARCO) FROM VENDEDORES);

/*VENDEDORES QUE VENDERAM MAIS DO QUE A MEDIA DE MARCO*/

SELECT NOME, MARCO
FROM VENDEDORES
WHERE MARCO > (SELECT AVG(MARCO) FROM VENDEDORES);

/*QUEM VENDEU MAIS EM MARCO DO SEXO MASCULINO*/

SELECT NOME, SEXO, MARCO
FROM VENDEDORES
WHERE MARCO = (SELECT MAX(MARCO) FROM VENDEDORES WHERE SEXO = 'M') AND SEXO = 'M';

/*QUEM VENDEU MENOS DO SEXO MASCULINO*/

SELECT NOME, SEXO, MARCO
FROM VENDEDORES
WHERE MARCO = (
			  SELECT MIN(MARCO)
			  FROM VENDEDORES
			  WHERE SEXO = 'F')
	AND SEXO = 'F';
	
/*RELATORIO DE VENDAS DO TRIMESTRE*/

SELECT NOME, 
	   JANEIRO,
	   FEVEREIRO,
	   MARCO,
	  (JANEIRO + FEVEREIRO + MARCO) AS TOTAL,
	  TRUNCATE((JANEIRO + FEVEREIRO + MARCO / 3),2) AS MEDIA_TRIMESTRAL
FROM VENDEDORES;
	  
