CREATE TABLE TABELA (
	COLUNA1 VARCHAR(30),
	COLUNA2 VARCHAR(30),
	COLUNA3 VARCHAR(30)
);

/*ADICIONANDO UMA PRIMARY KEY*/
ALTER TABLE TABELA
ADD PRIMARY KEY (COLUNA1);

/*ORGANIZAÇÃO DE CHAVES - CONSTRAINTS(CHAVES)*/

CREATE TABLE CLIENTE(
	IDCLIENTE INT,
	NOME VARCHAR(30)
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT, 
	TIPO CHAR(3) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT
);

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE
PRIMARY KEY(IDCLIENTE);

ALTER TABLE TELEFONE ADD CONSTRAINT FK_CLIENTE_TELEFONE
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE);

/* ACHANDO A TABELA DE CONSTRAINTS*/

SHOW DATABASES;

USE INFORMATION_SCHEMA;

DESC TABLE_CONSTRAINTS;

SELECT TABLE_SCHEMA, CONSTRAINT_TYPE, CONSTRAINT_NAME
FROM TABLE_CONSTRAINTS;


