CREATE DATABSE AULA40;

USE AULA40;

CREATE TABLE USARIO(
	IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	LOGIN VARCHAR(30),
	SENHA VARCHAR(100)
);

/*CRAINDO TABELA DE BACKUP*/

CREATE TABLE BKP_USUARIO(
	IDBACKUP INT PRIMARY KEY AUTO_INCREMENT, 
	IDUSUARIO INT,
	NOME VARCHAR(30),
	LOGIN VARCHAR(30)
);

/*CRIANDO A TRIGGER*/


CREATE TRIGGER BACKUP_USUARIO
BEFORE DELETE ON USUARIO
FOR EACH ROW
BEGIN
	INSERT INTO BKP_USUARIO VALUES(NULL, OLD.IDUSUARIO, OLD.NOME, OLD.LOGIN);
END
$

RENAME TABLE USARIO TO USUARIO$

INSERT INTO USUARIO VALUES(NULL, 'ALEXANDRE', 'ALEXANDREE', 'ANNACECI10');
INSERT INTO USUARIO VALUES(NULL, 'DANIELA', 'DANI12', 'FLAMENGO');

DELETE FROM USUARIO
WHERE IDUSUARIO = 1;

SELECT * FROM BKP_USUARIO;