DROP DATABASE LOJA; 

DROP DATABASE BACKUP;

CREATE DATABASE LOJA;

USE LOJA;

CREATE TABLE PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	VALOR FLOAT(10,2)
);

INSERT INTO PRODUTO VALUES(NULL, 'GELADEIRA', 2300);
INSERT INTO PRODUTO VALUES(NULL, 'CELULAR', 1300);
INSERT INTO PRODUTO VALUES(NULL, 'TABLET', 1500);
INSERT INTO PRODUTO VALUES(NULL, 'CADEIRA GAMER', 900);
INSERT INTO PRODUTO VALUES(NULL, 'ARMÁRIO', 750.21);
INSERT INTO PRODUTO VALUES(NULL, 'NOTEBOOK', 2700);

/*COMANDO QUE MOSTRA DATA E HORA*/
SELECT NOW();

/*COMANDO QUE USUÁRIO ESTA LOGADO E A MAQUINA*/
SELECT CURRENT_USER();


CREATE DATABASE BACKUP;

USE BACKUP;

CREATE TABLE BKP_PRODUTO(
	IDBACKUP INT PRIMARY KEY AUTO_INCREMENT,
	IDPRODUTO INT,
	NOME VARCHAR(30),
	VALOR_ORIGINAL FLOAT(10,2),
	VALOR_ALTERADO FLOAT(10,2),
	DATA DATETIME,
	USUARIO VARCHAR(30),
	EVENTO CHAR(1)
);

USE LOJA;

SELECT * FROM PRODUTO;

DELIMITER $

CREATE TRIGGER AUDIT_PRODUTO
AFTER UPDATE ON PRODUTO
FOR EACH ROW
BEGIN
	INSERT INTO BACKUP.BKP_PRODUTO VALUES(NULL, OLD.IDPRODUTO, OLD.NOME, OLD.VALOR,
	NEW.VALOR, NOW(), CURRENT_USER(), 'U');
END
$

UPDATE PRODUTO SET VALOR = 1900
WHERE IDPRODUTO = 2;

SELECT * FROM BACKUP.BKP_PRODUTO;